### PR TITLE
Restructure the repository and handle addon files

### PR DESCRIPTION
**Pull request by marcinn**
Solves #59

### CODE REVIEW

**Comment by JezSonic** [comment]
I still don't really like the idea of having dependencies in the root folder and copying them over instead of just having them in a `demo/`.

There's a high chance to overwrite files by mistake and having copy of that just makes kinda no sense to me.

I haven't look through everything yet and checked it all, will get to that in a few hours

**Comment by marcinn** [comment]
Demo is just a project which can disappear from this repo. All sources must be outside the project, because this is an addon. Just imagine that there is no demo folder.

The same issue will be with the Game and MSED repositories, because libmaszyna will not be stored under project's addons dir.


> There's a high chance to overwrite files by mistake and having copy of that just makes kinda no sense to me.

Yes. This is the case for all dependencies, which will be under your development, when you switch to the target project (Game or Editor). To solve this case you can use symlinks (the easiest and straightforward way). You can use them on Windows by enabling developer mode. 
You can also create tools you like, i.e. a script which will copy back files from demo/addons/libmaszyna (or other project you will work with) to the addon sources dir, maybe automatically based on inotify.
Or maybe you will develop on the source files, and there will be a script based on inotify, which will automatically run scons after detecting changes.

It is up to you. Personally I would stick with symlinks, but they will not be committed to the repository.

**Comment by marcinn** [comment]
Switching to draft.

> For easier development will be possible to use symlink

It works for existing files, however Scons is **DELETING** your new files during next build. This is unacceptable.  This build system should burn in the hell.

I will try to avoid this shit by checking for the existence of the symlink.

**Comment by marcinn** [comment]
applied workaround

**Comment by JezSonic** [comment]
> Demo is just a project which can disappear from this repo. All sources must be outside the project, because this is an addon. Just imagine that there is no demo folder.
> 
> The same issue will be with the Game and MSED repositories, because libmaszyna will not be stored under project's addons dir.
> 
> > There's a high chance to overwrite files by mistake and having copy of that just makes kinda no sense to me.
> 
> Yes. This is the case for all dependencies, which will be under your development, especially when you switch to the target project (Game or Editor). To solve this case you can use symlinks (the easiest and straightforward way). You can use them on Windows by enabling developer mode. You can also create tools you like, i.e. a script which will copy back files from demo/addons/libmaszyna (or other project you will work with) to the addon sources dir, maybe automatically based on inotify. Or maybe you will develop with the source files, and there will be a script based on inotify, which will automatically run scons after detecting changes.
> 
> It is up to you. Personally I would stick with symlinks, but they will not be committed to the repository.

K, thx for clarification

**Review by JezSonic — APPROVED** [review]
Seems good to me

**Review by carmel4a — APPROVED** [review]
As I've told on discord. I'm not sure if .gitigore and few commits from main merged successfully, but it seems to be ok.

**Pull request merged**
