### PR TITLE
Setup .gitattributes

### PR DESCRIPTION
**Pull request by JezSonic**

### CODE REVIEW

**Comment by marcinn** [comment]
1. Was the repo renormalized? https://stackoverflow.com/a/47580886
2. Even if git normalizes line endings, appropriate configuration should be set in the IDE so that local diffs are not too large. Please consider adding eol rule to `.editorconfig` https://editorconfig.org/, and also minimal configuration for vscode.

**Comment by JezSonic** [comment]
@marcinn 
> 1. Was the repo renormalized? https://stackoverflow.com/a/47580886
No, will be when `.editorconfig` and `.gitattributes` files will be approved. Then I'll do renormalization on this PR
> 2. Even if git normalizes line endings, appropriate configuration should be set in the IDE so that local diffs are not too large. Please consider adding eol rule to `.editorconfig` https://editorconfig.org/, and also minimal configuration for vscode.
Done

**Comment by marcinn** [comment]
Please rebase & drop commits:
* ad9353313954f6724d8b52010a38af9882be880a
* 4690e724c3e6bd2262d08510c9b176fcc3498e8e
* d42ee80c3f609eca8e9dcc4671a29a1b72ff40f1
* 77fe7545a168f36798ca261e669ae0ec163abb6e
* 7d8f32b72c72d80f6be8d1898b8d2ad4397f3c7d

----

> No, will be when .editorconfig and .gitattributes files will be approved. Then I'll do renormalization on this PR

AFAIK renormalization will be a pure diff, which should be a part of this PR.

**Review by marcinn — APPROVED** [review]

**Review by carmel4a — APPROVED** [review]
+1

**Pull request merged**
